import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getLocale } from "next-intl/server";

import AuthGuard from "@/app/auth/auth-guard";
import LanguageSwitcher from "@/app/component/languageSwitcher";
import Navbar from "@/app/component/navbar";
import AdminTabBar from "./admin-tab-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <AdminTabBar locale={locale} />
        <LanguageSwitcher />
        <AuthGuard
          redirectTo={`/${locale}`}
          allowedRoles={["admin"]}
          roleRedirects={{
            audit: `/${locale}/auditdashboard`,
            company: `/${locale}/companydashboard`,
          }}
        >
          {children}
        </AuthGuard>
      </body>
    </html>
  );
}
